Feat/weather
WhereIsPumpkin/EcoTracker pull request #2
Opened 2023-12-01 06:44 UTC by mmchedlidze

2023-12-01 07:09 UTC, NavrozashviliDamiane approved these changes
Perfect!

2023-12-01 10:41 UTC, likanozadze commented on EcoTracker App/Models/ModelWeather.swift
> +}
აქ ყველგან codable გჭირდება? ნანა სულ decodable-ს გვაწერინებს ხოლმე და ნახება აბა

2023-12-01 10:45 UTC, likanozadze approved these changes
great job

2023-12-01 11:10 UTC, WhereIsPumpkin commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +    }
extensionში რომ გქონდეს გატანილი ეს weatherViewDelegate უკეთესი იქნებოდა წაკითხვადობის მხრივ. დანარჩენი
კარგად გაქვს ყველაფერი!

2023-12-01 11:11 UTC, WhereIsPumpkin commented on EcoTracker App/Models/ModelWeather.swift
> +}
სწორად თქვა ლიკამ Codable არ არის საჭირო

2023-12-01 11:13 UTC, WhereIsPumpkin commented on EcoTracker App/Models/ModelWeather.swift
> +}
რასაც არ იყენებ, ჯობია არც დაწერო მოდელში

2023-12-01 11:14 UTC, WhereIsPumpkin requested changes
ყველაფერი ძალიან კარგად გაქვს. ერთი-ორი პატარა კომენტარი მიგიწერე თუ ჩაასწორებ კარგი იქნება

2023-12-01 11:29 UTC, mmchedlidze commented on EcoTracker App/Models/ModelWeather.swift
> +}
კი მართალია არ გვჭირდება ამ აპისთვის ნამდვილად codable. -DONE

2023-12-01 11:29 UTC, mmchedlidze commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +    }
გუდ ფოინთ! - DONE

2023-12-01 11:47 UTC, mmchedlidze commented on EcoTracker App/Models/ModelWeather.swift
> +}
-DONE

2023-12-01 11:50 UTC, anachikhladze commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +    // MARK: ElementsSetup
MARK-ები ესე შეგიძლია დაწერო: MARK: - კანტს უკეთებს და ვიზუალურად უფრო ლამაზია.

2023-12-01 11:53 UTC, WhereIsPumpkin approved these changes

2023-12-01 11:57 UTC, merged

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +    private func UIsetup() {
uppercase ით არდაიწყო მეთოდის სახელი
setupUI

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +    private func UIAddview() {
არც აქ არც ქვემოთ სადაც მსგავსად გაქვს

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +        cityLabel.translatesAutoresizingMaskIntoConstraints = false
სტეკშია და არუნდა ეს

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +        temperatureLabel.translatesAutoresizingMaskIntoConstraints = false
არც ამას

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +        weatherTypeLabel.translatesAutoresizingMaskIntoConstraints = false
არც ამას

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +        generateWeatherButton.addTarget(self, action: #selector(buttonTapped), for: .touchUpInside)
addAction

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewController.swift
> +        viewModel.buttonTapped(latitudeText: latitudeTextField.text, longitudeText: longitudeTextField.text)
რა button? უფრო კონკრეტული სახელი დაარქვი

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewModel.swift
> +import UIKit
ამის იმპორტი ვიუმოდელში არუნდაგჭირდებოდეს წესით

2023-12-05 18:27 UTC, NanaJimsheleishvili commented on EcoTracker App/Scenes/Weather/WeatherViewModel.swift
> +    private func getWeather(latitude: Double, longitude: Double, completion: @escaping (Result<WeatherData, Error>) -> Void) {
ეს ქვემოთ დაწერე buttonTapped ამ მეთოდის შემდეგ